### ISSUE TITLE
C3D data file.

### ISSUE THREAD

**Issue by Abdullah00Alharthi** [sebastian-lapuschkin/interpretable-deep-gait#1]
Hi, 

Thanks for sharing  awesome toolbox and data! I am just a beginner of artificial neural networks. I have a  struggle with processing the C3D raw data file. I used the following code to red the C3D file in python :

import c3d
reader = c3d.Reader(open('S1_0003_Gait.c3d', 'rb'))
for i, points, analog in reader.read_frames():
    print('frame {}: point {}, analog {}'.format(i, points.shape, analog.shape))
    
However, I am not sure what is the input of the neural network as I have analog and points. 

Can you please explain how to feed the C3D files to the ANN. I see you have processed the C3D and generated the .mat file, but I am interested in using the C3D file.   

 Many thanks!!!

**Comment by sebastian-lapuschkin** [comment]
Hey there, 

are those c3d files related to our publication?
Regarding c3d data processing I would forward this question to my colleague @fabian-horst 

best,

**Comment by Abdullah00Alharthi** [comment]
Many thanks for your reply, 

Yes the data at (https://data.mendeley.com/datasets/svx74xcrjr/1) of this paper is in c3d format, and I am interested in processing the C3D file for ANN.

**Comment by sebastian-lapuschkin** [comment]
Ah I see.
@fabian-horst , do you think you can add the scripts you have created for generating the `.mat`-files used in our experiments to this repo?

best,

**Comment by fabian-horst** [comment]
Hi,
I used the commercial biomechanics software Visual3D [(Link)](https://c-motion.com/products/visual3d) to process the data. The file `python/Gait_GRF_JA_Label.mat` contains the processed, ready for use ground reaction force and joint angle data. Is this data suitable for your application? 
To realize the entire processing based on the raw data in Phyton involves quite a lot of work. I don't have any ready to use scripts available for this at the moment. If you describe in more detail what exactly you are planning to do, I can try to support you and possibly generate the desired data for you. In this context, the following links might be helpful: BTK Toolbox [(Link)](http://biomechanical-toolkit.github.io/) and the Conventional Gait Model [(Link)](https://pycgm2.github.io/).
best,
Fabian

**Comment by Abdullah00Alharthi** [comment]
Sebastian, Fabian, 

Thank you so much for the help. 
Fabian, I was able to generate a text file using Mokka in BTK Toolbox. Now I can import the text file into python and process the data. 

Great fan of your work by the way. 

Cheers,

Aalharthi
